#!/usr/bin/env bash
# qa-verdict-gate.sh — TaskCompleted hook: block task close until QA report shows Verdict: PASS
# Generated by piloth-team-setup. Copied to .claude/scripts/qa-verdict-gate.sh during setup Stage 9.
# Deactivate: remove from .claude/settings.json hooks.TaskCompleted array.
set -euo pipefail

# Parse hook payload
PAYLOAD="${CLAUDE_HOOK_PAYLOAD:-}"
[ -z "$PAYLOAD" ] && exit 0  # No payload — nothing to gate

TASK_ID=$(echo "$PAYLOAD" | jq -r '.taskId // ""')
TASK_TITLE=$(echo "$PAYLOAD" | jq -r '.title // ""')

# Only validate team-task IDs (pattern: YYYYMMDD-<slug>)
# Skip user-created todos, non-team tasks, etc.
echo "$TASK_ID" | grep -qE '^[0-9]{8}-[a-z][a-z0-9-]+$' || exit 0

# Look for QA report
QA_REPORT="tests/qa/qa-report-${TASK_ID}.md"
if [ ! -f "$QA_REPORT" ]; then
  cat >&2 <<EOF
QA verdict gate: missing $QA_REPORT
Task "$TASK_TITLE" cannot complete without a QA report.
Action: have QA member produce report at $QA_REPORT, or override via /<command> with explicit user approval.
EOF
  exit 2
fi

# Check verdict — accepts "PASS" and "PASS WITH NOTES" (prefix match)
if ! grep -qE '^\*\*Verdict:\*\*\s*PASS' "$QA_REPORT"; then
  VERDICT=$(grep -E '^\*\*Verdict:\*\*' "$QA_REPORT" | head -1)
  cat >&2 <<EOF
QA verdict gate: $QA_REPORT verdict is not PASS
Found: $VERDICT
Action: address QA findings, re-run QA, or override with explicit user approval.
EOF
  exit 2
fi

exit 0
