# ------------------------------------------------ codebase intelligence

# This stdlib reference engine locks Piloth's adapter-neutral contract. The
# maintained native fork can replace indexing/query execution behind the same
# SQLite/JSON boundary without moving orchestration into adapters.
CODEBASE_SCHEMA_VERSION = 2
CODEBASE_CONTRACT_VERSION = 1
CODEBASE_ENGINE_VERSION = 1
CODEBASE_DEFAULT_MAX_FILES = 50000
CODEBASE_DEFAULT_MAX_TOTAL_BYTES = 512 * 1024 * 1024
CODEBASE_MAX_FILE_BYTES = 2 * 1024 * 1024
CODEBASE_SKIP_DIRS = {
    ".git", ".hg", ".svn", ".venv", "venv", "__pycache__", "node_modules",
    "vendor", "dist", "build", ".next", ".turbo", "coverage",
}
CODEBASE_GENERATED_MARKERS = (
    "generated file", "do not edit", "auto-generated", "autogenerated",
    "code generated",
)
CODEBASE_LANGUAGES = {
    ".py": "Python", ".pyi": "Python", ".js": "JavaScript", ".jsx": "JavaScript",
    ".mjs": "JavaScript", ".cjs": "JavaScript", ".ts": "TypeScript",
    ".tsx": "TypeScript", ".go": "Go", ".rs": "Rust", ".java": "Java",
    ".kt": "Kotlin", ".kts": "Kotlin", ".c": "C", ".h": "C/C++",
    ".cc": "C++", ".cpp": "C++", ".cxx": "C++", ".hpp": "C++",
    ".cs": "C#", ".php": "PHP", ".rb": "Ruby", ".swift": "Swift",
    ".scala": "Scala", ".sh": "Shell", ".bash": "Shell", ".zsh": "Shell",
    ".sql": "SQL", ".html": "HTML", ".css": "CSS", ".scss": "SCSS",
    ".vue": "Vue", ".svelte": "Svelte", ".dart": "Dart", ".ex": "Elixir",
    ".exs": "Elixir", ".erl": "Erlang", ".hrl": "Erlang", ".hs": "Haskell",
    ".lua": "Lua", ".r": "R", ".R": "R", ".m": "Objective-C/MATLAB",
    ".mm": "Objective-C++", ".pl": "Perl", ".pm": "Perl", ".fs": "F#",
    ".fsx": "F#", ".clj": "Clojure", ".cljs": "Clojure", ".zig": "Zig",
    ".sol": "Solidity", ".tf": "HCL", ".proto": "Protobuf", ".graphql": "GraphQL",
    ".gql": "GraphQL", ".yaml": "YAML", ".yml": "YAML", ".toml": "TOML",
    ".json": "JSON", ".xml": "XML", ".md": "Markdown", ".rst": "reStructuredText",
}


def codebase_index_paths():
    """Resolve state paths dynamically so controlled-target tests can rebind roots."""
    state_dir = PILOTHOS_DIR / "memory" / "state" / "codebase-index"
    return state_dir, state_dir / "index.sqlite3"


def codebase_safe_index_paths():
    state_dir, db_path = codebase_index_paths()
    try:
        root = REPO_ROOT.resolve()
        if state_dir.is_symlink() or db_path.is_symlink():
            return None, None, "codebase index state must not use symlinks"
        resolved_parent = state_dir.parent.resolve()
        if os.path.commonpath((str(root), str(resolved_parent))) != str(root):
            return None, None, "codebase index state escapes repository root"
        if state_dir.exists():
            resolved_state = state_dir.resolve()
            if os.path.commonpath((str(root), str(resolved_state))) != str(root):
                return None, None, "codebase index state escapes repository root"
    except (OSError, ValueError) as exc:
        return None, None, f"cannot validate codebase index state: {exc}"
    return state_dir, db_path, None


def codebase_repo(payload):
    raw = str((payload or {}).get("repo_path") or REPO_ROOT)
    try:
        requested = pathlib.Path(raw).expanduser().resolve()
        controlled = REPO_ROOT.resolve()
    except OSError as exc:
        return None, f"cannot resolve repo_path: {exc}"
    if requested != controlled:
        return None, "repo_path must be the Piloth-controlled consumer repository"
    if not requested.is_dir():
        return None, "repo_path is not a directory"
    return requested, None


def codebase_git(root, *args, timeout=10):
    try:
        return subprocess.run(
            ["git", "-C", str(root), *args],
            capture_output=True, text=True, timeout=timeout, check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None


def codebase_git_state(root):
    head_run = codebase_git(root, "rev-parse", "HEAD")
    head = head_run.stdout.strip() if head_run and head_run.returncode == 0 else ""
    status_run = codebase_git(
        root, "status", "--porcelain=v1", "-z", "--untracked-files=all")
    if not status_run or status_run.returncode != 0:
        return {"git": False, "head": "", "worktree": "", "dirty_paths": []}
    raw = status_run.stdout
    dirty = []
    for item in raw.split("\0"):
        if len(item) >= 4:
            rel = item[3:].strip()
            if rel and " -> " in rel:
                rel = rel.rsplit(" -> ", 1)[-1]
            if rel:
                dirty.append(rel)
    digest = hashlib.sha256(raw.encode("utf-8", errors="replace"))
    for rel in sorted(set(dirty)):
        path = root / rel
        try:
            if path.is_file() and not path.is_symlink():
                digest.update(rel.encode("utf-8"))
                digest.update(hashlib.sha256(path.read_bytes()).digest())
        except OSError:
            digest.update(f"{rel}:missing".encode("utf-8"))
    return {
        "git": True,
        "head": head,
        "worktree": digest.hexdigest(),
        "dirty_paths": sorted(set(dirty)),
    }


def codebase_fallback_paths(root):
    paths = []
    state_dir, _ = codebase_index_paths()
    for current, dirs, names in os.walk(root, topdown=True, followlinks=False):
        current_path = pathlib.Path(current)
        dirs[:] = sorted(
            name for name in dirs
            if name not in CODEBASE_SKIP_DIRS
            and not (current_path / name).is_symlink()
        )
        for name in sorted(names):
            path = current_path / name
            try:
                if path.is_symlink() or state_dir in path.parents:
                    continue
                paths.append(path.relative_to(root).as_posix())
            except (OSError, ValueError):
                continue
    return paths


def codebase_discover_paths(root):
    tracked = codebase_git(
        root, "ls-files", "-z", "--cached", "--others", "--exclude-standard")
    if tracked and tracked.returncode == 0:
        candidates = sorted(set(filter(None, tracked.stdout.split("\0"))))
    else:
        candidates = codebase_fallback_paths(root)
    state_rel = "pilothOS/memory/state/codebase-index/"
    paths = []
    for rel in candidates:
        if rel.startswith(state_rel):
            continue
        parts = pathlib.PurePosixPath(rel).parts
        if any(part in CODEBASE_SKIP_DIRS for part in parts[:-1]):
            continue
        paths.append(rel)
    return paths


def codebase_generated_source(data):
    header = data[:16384].decode("utf-8", errors="ignore").lower()
    return any(marker in header for marker in CODEBASE_GENERATED_MARKERS)


def codebase_file_record(root, rel):
    path = root / rel
    try:
        resolved = path.resolve()
        if os.path.commonpath((str(root), str(resolved))) != str(root):
            return None, ("excluded", "path escapes repository root")
        if path.is_symlink() or not path.is_file():
            return None, ("excluded", "symlink or non-file")
        stat = path.stat()
        if stat.st_size > CODEBASE_MAX_FILE_BYTES:
            return None, ("skipped", f"file exceeds {CODEBASE_MAX_FILE_BYTES} bytes")
        data = path.read_bytes()
    except OSError as exc:
        return None, ("skipped", f"read failed: {exc}")
    if b"\0" in data[:8192]:
        return None, ("excluded", "binary content")
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        text = data.decode("utf-8", errors="replace")
    suffix = path.suffix
    language = CODEBASE_LANGUAGES.get(suffix, "Text")
    return {
        "path": rel,
        "language": language,
        "size": stat.st_size,
        "mtime_ns": stat.st_mtime_ns,
        "sha256": hashlib.sha256(data).hexdigest(),
        "generated": codebase_generated_source(data),
        "text": text,
    }, None


def codebase_module_name(rel):
    path = pathlib.PurePosixPath(rel)
    without_suffix = str(path.with_suffix("")) if path.suffix else str(path)
    return without_suffix.replace("/", ".").replace("-", "_")


def codebase_call_name(node):
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return ""


def codebase_signature(source_lines, node):
    if node.lineno <= 0 or node.lineno > len(source_lines):
        return ""
    line = source_lines[node.lineno - 1].strip()
    return line[:500]


class CodebasePythonVisitor(ast.NodeVisitor):
    def __init__(self, module, source):
        self.module = module
        self.lines = source.splitlines()
        self.scope = []
        self.symbols = []
        self.calls = []
        self.imports = []

    def current_qn(self):
        return ".".join([self.module, *self.scope])

    def record_definition(self, node, kind):
        qn = ".".join([self.module, *self.scope, node.name])
        self.symbols.append({
            "kind": kind,
            "name": node.name,
            "qualified_name": qn,
            "start_line": node.lineno,
            "end_line": getattr(node, "end_lineno", node.lineno),
            "signature": codebase_signature(self.lines, node),
            "body_hash": hashlib.sha256(
                ast.dump(node, annotate_fields=True, include_attributes=False).encode("utf-8")
            ).hexdigest(),
        })
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    def visit_ClassDef(self, node):
        self.record_definition(node, "Class")

    def visit_FunctionDef(self, node):
        self.record_definition(node, "Function" if not self.scope else "Method")

    def visit_AsyncFunctionDef(self, node):
        self.record_definition(node, "Function" if not self.scope else "Method")

    def visit_Call(self, node):
        callee = codebase_call_name(node.func)
        if callee:
            self.calls.append({
                "caller_qn": self.current_qn(),
                "callee": callee,
                "line": getattr(node, "lineno", 0),
            })
        self.generic_visit(node)

    def visit_Import(self, node):
        for alias in node.names:
            self.imports.append((alias.name, alias.asname or "", node.lineno))

    def visit_ImportFrom(self, node):
        module = node.module or ""
        for alias in node.names:
            target = f"{module}.{alias.name}".strip(".")
            self.imports.append((target, alias.asname or alias.name, node.lineno))


def codebase_parse_record(record):
    module = codebase_module_name(record["path"])
    module_symbol = {
        "kind": "Module",
        "name": pathlib.PurePosixPath(record["path"]).name,
        "qualified_name": module,
        "start_line": 1,
        "end_line": max(len(record["text"].splitlines()), 1),
        "signature": "",
        "body_hash": "",
    }
    if record["language"] != "Python":
        return [module_symbol], [], [], ("shallow", "no deep language adapter in reference engine")
    try:
        tree = ast.parse(record["text"], filename=record["path"])
    except (SyntaxError, ValueError) as exc:
        detail = f"{type(exc).__name__} at line {getattr(exc, 'lineno', 0) or 0}"
        return [module_symbol], [], [], ("partial", detail)
    visitor = CodebasePythonVisitor(module, record["text"])
    visitor.visit(tree)
    return [module_symbol, *visitor.symbols], visitor.calls, visitor.imports, ("deep", "")


def codebase_create_schema(db):
    db.executescript("""
        PRAGMA journal_mode=OFF;
        PRAGMA synchronous=OFF;
        CREATE TABLE metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL);
        CREATE TABLE files (
            id INTEGER PRIMARY KEY, path TEXT UNIQUE NOT NULL, language TEXT NOT NULL,
            size INTEGER NOT NULL, mtime_ns INTEGER NOT NULL, sha256 TEXT NOT NULL,
            is_generated INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE coverage (
            path TEXT PRIMARY KEY, status TEXT NOT NULL, detail TEXT NOT NULL DEFAULT ''
        );
        CREATE TABLE symbols (
            id INTEGER PRIMARY KEY, file_id INTEGER NOT NULL, kind TEXT NOT NULL,
            name TEXT NOT NULL, qualified_name TEXT NOT NULL,
            start_line INTEGER NOT NULL, end_line INTEGER NOT NULL,
            signature TEXT NOT NULL DEFAULT '', body_hash TEXT NOT NULL DEFAULT '',
            is_generated INTEGER NOT NULL DEFAULT 0, canonical_symbol_id INTEGER
        );
        CREATE TABLE edges (
            id INTEGER PRIMARY KEY, source_symbol_id INTEGER NOT NULL,
            target_symbol_id INTEGER NOT NULL, type TEXT NOT NULL,
            confidence REAL NOT NULL, evidence TEXT NOT NULL DEFAULT '',
            UNIQUE(source_symbol_id, target_symbol_id, type)
        );
        CREATE TABLE raw_calls (
            caller_qn TEXT NOT NULL, callee TEXT NOT NULL, line INTEGER NOT NULL
        );
        CREATE TABLE imports (
            file_id INTEGER NOT NULL, module TEXT NOT NULL,
            alias TEXT NOT NULL DEFAULT '', line INTEGER NOT NULL
        );
        CREATE INDEX symbols_name ON symbols(name);
        CREATE INDEX symbols_qn ON symbols(qualified_name);
        CREATE INDEX edges_source ON edges(source_symbol_id, type);
        CREATE INDEX edges_target ON edges(target_symbol_id, type);
    """)


def codebase_insert_record(db, record, symbols, calls, imports, coverage):
    cursor = db.execute(
        "INSERT INTO files(path,language,size,mtime_ns,sha256,is_generated) VALUES(?,?,?,?,?,?)",
        (record["path"], record["language"], record["size"], record["mtime_ns"],
         record["sha256"], int(record["generated"])),
    )
    file_id = cursor.lastrowid
    module_id = None
    for symbol in symbols:
        inserted = db.execute(
            """INSERT INTO symbols(
                file_id,kind,name,qualified_name,start_line,end_line,signature,body_hash,is_generated
            ) VALUES(?,?,?,?,?,?,?,?,?)""",
            (file_id, symbol["kind"], symbol["name"], symbol["qualified_name"],
             symbol["start_line"], symbol["end_line"], symbol["signature"],
             symbol["body_hash"], int(record["generated"])),
        ).lastrowid
        if symbol["kind"] == "Module":
            module_id = inserted
        elif module_id:
            db.execute(
                "INSERT OR IGNORE INTO edges VALUES(NULL,?,?,?,?,?)",
                (module_id, inserted, "DEFINES", 1.0, record["path"]),
            )
    db.executemany(
        "INSERT INTO raw_calls(caller_qn,callee,line) VALUES(?,?,?)",
        [(call["caller_qn"], call["callee"], call["line"]) for call in calls],
    )
    db.executemany(
        "INSERT INTO imports(file_id,module,alias,line) VALUES(?,?,?,?)",
        [(file_id, module, alias, line) for module, alias, line in imports],
    )
    db.execute(
        "INSERT OR REPLACE INTO coverage(path,status,detail) VALUES(?,?,?)",
        (record["path"], coverage[0], coverage[1]),
    )


def codebase_canonicalize_duplicates(db):
    groups = db.execute(
        """SELECT kind,name,body_hash FROM symbols
           WHERE body_hash <> '' GROUP BY kind,name,body_hash
           HAVING SUM(is_generated) > 0 AND SUM(is_generated) < COUNT(*)"""
    ).fetchall()
    aliases = 0
    for kind, name, body_hash in groups:
        rows = db.execute(
            """SELECT s.id,s.is_generated,f.path FROM symbols s
               JOIN files f ON f.id=s.file_id
               WHERE s.kind=? AND s.name=? AND s.body_hash=?""",
            (kind, name, body_hash),
        ).fetchall()
        sources = sorted(
            (row for row in rows if not row[1]),
            key=lambda row: (len(row[2]), row[2]),
        )
        canonical = sources[0][0]
        for row in rows:
            if not row[1]:
                continue
            db.execute(
                "UPDATE symbols SET canonical_symbol_id=? WHERE id=?",
                (canonical, row[0]),
            )
            aliases += 1
    return aliases


def codebase_resolve_calls(db):
    resolved = 0
    unresolved = 0
    for caller_qn, callee, line in db.execute(
            "SELECT caller_qn,callee,line FROM raw_calls").fetchall():
        caller = db.execute(
            """SELECT id,file_id FROM symbols
               WHERE qualified_name=? AND canonical_symbol_id IS NULL
               ORDER BY is_generated,start_line DESC,id DESC LIMIT 1""",
            (caller_qn,),
        ).fetchone()
        if not caller:
            unresolved += 1
            continue
        candidates = db.execute(
            """SELECT id,file_id FROM symbols
               WHERE name=? AND canonical_symbol_id IS NULL
               AND kind IN ('Function','Method','Class')""",
            (callee,),
        ).fetchall()
        local = [candidate for candidate in candidates if candidate[1] == caller[1]]
        chosen = local[0] if len(local) == 1 else (
            candidates[0] if len(candidates) == 1 else None)
        if not chosen:
            unresolved += 1
            continue
        confidence = 1.0 if chosen in local else 0.8
        db.execute(
            "INSERT OR IGNORE INTO edges VALUES(NULL,?,?,?,?,?)",
            (caller[0], chosen[0], "CALLS", confidence, f"line:{line}"),
        )
        resolved += 1
    return resolved, unresolved


def codebase_write_metadata(db, values):
    db.executemany(
        "INSERT INTO metadata(key,value) VALUES(?,?)",
        [(key, str(value)) for key, value in values.items()],
    )


def codebase_index_payload(payload):
    if not isinstance(payload, dict):
        return {"result": "codebase_index_rejected", "errors": ["payload must be an object"]}
    root, error = codebase_repo(payload)
    if error:
        return {"result": "codebase_index_rejected", "errors": [error]}
    try:
        max_files = int(payload.get("max_files", CODEBASE_DEFAULT_MAX_FILES))
        max_total_bytes = int(
            payload.get("max_total_bytes", CODEBASE_DEFAULT_MAX_TOTAL_BYTES))
    except (TypeError, ValueError):
        return {
            "result": "codebase_index_rejected",
            "errors": ["max_files and max_total_bytes must be integers"],
        }
    paths = codebase_discover_paths(root)
    if max_files < 1 or len(paths) > max_files:
        return {
            "result": "codebase_index_refused",
            "file_count": len(paths),
            "max_files": max_files,
            "errors": ["repository exceeds the explicit indexing file budget"],
        }
    if max_total_bytes < 1:
        return {
            "result": "codebase_index_refused",
            "max_total_bytes": max_total_bytes,
            "errors": ["max_total_bytes must be positive"],
        }
    state_dir, db_path, state_error = codebase_safe_index_paths()
    if state_error:
        return {"result": "codebase_index_rejected", "errors": [state_error]}
    state_dir.mkdir(parents=True, exist_ok=True)
    state_dir, db_path, state_error = codebase_safe_index_paths()
    if state_error:
        return {"result": "codebase_index_rejected", "errors": [state_error]}
    os.chmod(state_dir, 0o700)
    tmp_path = state_dir / f".index-{os.getpid()}.sqlite3"
    return codebase_build_index(
        root, paths, tmp_path, db_path, max_total_bytes=max_total_bytes)


def codebase_update_content_digest(digest, record):
    digest.update(record["path"].encode("utf-8"))
    digest.update(b":")
    digest.update(record["sha256"].encode("ascii"))
    digest.update(b"\0")


def codebase_discard_index(db, tmp_path):
    if db:
        try:
            db.close()
        except sqlite3.Error:
            pass
    try:
        tmp_path.unlink(missing_ok=True)
    except OSError:
        pass


def codebase_build_index(root, paths, tmp_path, db_path, max_total_bytes):
    git_state = codebase_git_state(root)
    structural = hashlib.sha256("\0".join(paths).encode()).hexdigest()
    content = hashlib.sha256()
    total_bytes = 0
    db = None
    try:
        if tmp_path.exists():
            tmp_path.unlink()
        db = sqlite3.connect(tmp_path)
        codebase_create_schema(db)
        for rel in paths:
            record, miss = codebase_file_record(root, rel)
            if miss:
                db.execute(
                    "INSERT OR REPLACE INTO coverage(path,status,detail) VALUES(?,?,?)",
                    (rel, miss[0], miss[1]),
                )
                continue
            total_bytes += record["size"]
            if total_bytes > max_total_bytes:
                raise OverflowError("repository exceeds the explicit indexing byte budget")
            codebase_update_content_digest(content, record)
            codebase_insert_record(db, record, *codebase_parse_record(record))
        aliases = codebase_canonicalize_duplicates(db)
        resolved, unresolved = codebase_resolve_calls(db)
        counts = codebase_db_counts(db)
        codebase_write_metadata(db, {
            "schema_version": CODEBASE_SCHEMA_VERSION,
            "contract_version": CODEBASE_CONTRACT_VERSION,
            "engine_version": CODEBASE_ENGINE_VERSION,
            "engine": "piloth-stdlib-reference",
            "repo_root": root,
            "indexed_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "git_head": git_state["head"],
            "worktree_fingerprint": git_state["worktree"],
            "structural_fingerprint": structural,
            "content_fingerprint": content.hexdigest(),
            "indexed_bytes": total_bytes,
            "generated_aliases": aliases,
            "resolved_calls": resolved,
            "unresolved_calls": unresolved,
        })
        db.commit()
        db.close()
        db = None
        os.chmod(tmp_path, 0o600)
        os.replace(tmp_path, db_path)
    except OverflowError as exc:
        codebase_discard_index(db, tmp_path)
        return {
            "result": "codebase_index_refused",
            "max_total_bytes": max_total_bytes,
            "indexed_bytes_before_refusal": total_bytes,
            "errors": [str(exc)],
        }
    except (OSError, sqlite3.Error, ValueError) as exc:
        codebase_discard_index(db, tmp_path)
        return {"result": "codebase_index_failed", "errors": [str(exc)]}
    return {
        "result": "codebase_indexed",
        "engine": "piloth-stdlib-reference",
        "database": str(db_path.relative_to(REPO_ROOT)),
        "files": counts["files"],
        "indexed_bytes": total_bytes,
        "symbols": counts["symbols"],
        "edges": counts["edges"],
        "coverage_gaps": counts["coverage_gaps"],
        "generated_aliases": aliases,
        "resolved_calls": resolved,
        "unresolved_calls": unresolved,
        "freshness": "fresh",
    }


def codebase_db_counts(db):
    files = db.execute("SELECT COUNT(*) FROM files").fetchone()[0]
    symbols = db.execute("SELECT COUNT(*) FROM symbols").fetchone()[0]
    edges = db.execute("SELECT COUNT(*) FROM edges").fetchone()[0]
    gaps = db.execute(
        "SELECT COUNT(*) FROM coverage WHERE status <> 'deep'").fetchone()[0]
    return {"files": files, "symbols": symbols, "edges": edges, "coverage_gaps": gaps}


def codebase_metadata(db):
    return dict(db.execute("SELECT key,value FROM metadata").fetchall())


def codebase_open():
    _, path, error = codebase_safe_index_paths()
    if error:
        return None, error
    if not path.exists():
        return None, "missing"
    try:
        db = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
        db.row_factory = sqlite3.Row
        return db, None
    except sqlite3.Error as exc:
        return None, str(exc)


def codebase_content_fingerprint(root, paths):
    digest = hashlib.sha256()
    for rel in paths:
        record, _ = codebase_file_record(root, rel)
        if record:
            codebase_update_content_digest(digest, record)
    return digest.hexdigest()


def codebase_status_payload(payload=None):
    root, error = codebase_repo(payload or {})
    if error:
        return {"result": "codebase_status_rejected", "errors": [error]}
    db, open_error = codebase_open()
    if not db:
        if open_error != "missing":
            return {
                "result": "codebase_status",
                "status": "invalid",
                "errors": [open_error],
            }
        return {
            "result": "codebase_status",
            "status": "missing",
            "recommendation": "index_when_structural_context_is_needed",
        }
    try:
        meta = codebase_metadata(db)
        counts = codebase_db_counts(db)
        git_state = codebase_git_state(root)
        current_paths = codebase_discover_paths(root)
        current_structural = hashlib.sha256("\0".join(current_paths).encode()).hexdigest()
        if int(meta.get("schema_version", 0)) != CODEBASE_SCHEMA_VERSION:
            status, reason = "invalid", "schema version does not match engine"
        elif int(meta.get("contract_version", 0)) != CODEBASE_CONTRACT_VERSION:
            status, reason = "invalid", "contract version does not match engine"
        elif int(meta.get("engine_version", 0)) != CODEBASE_ENGINE_VERSION:
            status, reason = "invalid", "engine version does not match index"
        elif meta.get("repo_root") != str(root):
            status, reason = "invalid", "repository root does not match index"
        elif git_state["head"] != meta.get("git_head", ""):
            status, reason = "stale_structural", "git HEAD changed"
        elif current_structural != meta.get("structural_fingerprint"):
            status, reason = "stale_structural", "indexed path set changed"
        elif git_state["worktree"] != meta.get("worktree_fingerprint", ""):
            status, reason = "stale_content", "working-tree content changed"
        elif not git_state["git"] and codebase_content_fingerprint(
                root, current_paths) != meta.get("content_fingerprint"):
            status, reason = "stale_content", "source content changed"
        else:
            status, reason = "fresh", "generation matches repository state"
    except (sqlite3.Error, ValueError) as exc:
        db.close()
        return {"result": "codebase_status", "status": "invalid", "errors": [str(exc)]}
    db.close()
    return {
        "result": "codebase_status",
        "status": status,
        "reason": reason,
        "recommendation": "use_index" if status == "fresh" else "full_rebuild",
        "engine": meta.get("engine", "unknown"),
        "schema_version": int(meta.get("schema_version", 0)),
        "engine_version": int(meta.get("engine_version", 0)),
        "indexed_at": meta.get("indexed_at", ""),
        **counts,
    }


def codebase_symbol_rows(db, query, limit):
    pattern = f"%{query.lower()}%"
    rows = db.execute(
        """SELECT s.id,s.kind,s.name,s.qualified_name,s.start_line,s.end_line,
                  s.signature,s.is_generated,f.path,
                  (SELECT COUNT(*) FROM symbols a WHERE a.canonical_symbol_id=s.id) alias_count
           FROM symbols s JOIN files f ON f.id=s.file_id
           WHERE s.canonical_symbol_id IS NULL
             AND (lower(s.name) LIKE ? OR lower(s.qualified_name) LIKE ?)
           ORDER BY CASE WHEN lower(s.name)=? THEN 0 ELSE 1 END,
                    s.is_generated, length(s.qualified_name), s.qualified_name
           LIMIT ?""",
        (pattern, pattern, query.lower(), limit),
    ).fetchall()
    return [dict(row) for row in rows]


def codebase_resolve_symbol(db, value):
    rows = db.execute(
        """SELECT s.id,s.kind,s.name,s.qualified_name,s.start_line,s.end_line,
                  s.file_id,f.path,f.sha256
           FROM symbols s JOIN files f ON f.id=s.file_id
           WHERE s.canonical_symbol_id IS NULL
             AND (s.qualified_name=? OR s.name=?)
           ORDER BY CASE WHEN s.qualified_name=? THEN 0 ELSE 1 END,
                    s.is_generated, s.qualified_name, s.start_line DESC
           LIMIT 25""",
        (value, value, value),
    ).fetchall()
    exact = [row for row in rows if row["qualified_name"] == value]
    if len(exact) == 1:
        return exact[0], []
    if exact and len({row["path"] for row in exact}) == 1:
        return exact[0], []
    if len(rows) == 1:
        return rows[0], []
    return None, [
        {"qualified_name": row["qualified_name"], "kind": row["kind"], "path": row["path"]}
        for row in rows
    ]


def codebase_query_overview(db, payload):
    counts = codebase_db_counts(db)
    languages = [
        {"language": row[0], "files": row[1]}
        for row in db.execute(
            "SELECT language,COUNT(*) FROM files GROUP BY language ORDER BY COUNT(*) DESC,language"
        ).fetchall()
    ]
    coverage = [
        {"status": row[0], "files": row[1]}
        for row in db.execute(
            "SELECT status,COUNT(*) FROM coverage GROUP BY status ORDER BY status"
        ).fetchall()
    ]
    return {"action": "overview", **counts, "languages": languages, "coverage": coverage}


def codebase_query_search(db, payload):
    query = str(payload.get("query", "")).strip()
    if not query:
        return {"action": "search", "errors": ["query is required"]}
    limit = min(max(int(payload.get("limit", 20)), 1), 200)
    rows = codebase_symbol_rows(db, query, limit)
    return {"action": "search", "query": query, "results": rows, "returned": len(rows)}


def codebase_trace_leg(db, seed, direction, depth, limit):
    frontier = {seed}
    seen = {seed}
    results = []
    for hop in range(1, depth + 1):
        if not frontier or len(results) >= limit:
            break
        placeholders = ",".join("?" for _ in frontier)
        if direction == "outbound":
            sql = f"""SELECT e.source_symbol_id,e.target_symbol_id,e.confidence,
                             s.qualified_name,s.kind,f.path
                      FROM edges e JOIN symbols s ON s.id=e.target_symbol_id
                      JOIN files f ON f.id=s.file_id
                      WHERE e.type='CALLS' AND e.source_symbol_id IN ({placeholders})
                      ORDER BY e.source_symbol_id,e.target_symbol_id"""
        else:
            sql = f"""SELECT e.target_symbol_id,e.source_symbol_id,e.confidence,
                             s.qualified_name,s.kind,f.path
                      FROM edges e JOIN symbols s ON s.id=e.source_symbol_id
                      JOIN files f ON f.id=s.file_id
                      WHERE e.type='CALLS' AND e.target_symbol_id IN ({placeholders})
                      ORDER BY e.target_symbol_id,e.source_symbol_id"""
        rows = db.execute(sql, tuple(frontier)).fetchall()
        next_frontier = set()
        for row in rows:
            target_id = row[1]
            if target_id in seen:
                continue
            seen.add(target_id)
            next_frontier.add(target_id)
            results.append({
                "qualified_name": row[3], "kind": row[4], "path": row[5],
                "hop": hop, "confidence": row[2],
            })
            if len(results) >= limit:
                break
        frontier = next_frontier
    return results


def codebase_query_trace(db, payload):
    value = str(payload.get("symbol", "")).strip()
    if not value:
        return {"action": "trace", "errors": ["symbol is required"]}
    symbol, suggestions = codebase_resolve_symbol(db, value)
    if not symbol:
        return {
            "action": "trace",
            "status": "ambiguous" if suggestions else "not_found",
            "suggestions": suggestions,
        }
    direction = str(payload.get("direction", "both")).lower()
    if direction not in {"inbound", "outbound", "both"}:
        return {"action": "trace", "errors": ["direction must be inbound, outbound or both"]}
    depth = min(max(int(payload.get("depth", 2)), 1), 5)
    limit = min(max(int(payload.get("limit", 100)), 1), 1000)
    result = {
        "action": "trace",
        "symbol": symbol["qualified_name"],
        "direction": direction,
    }
    if direction in {"outbound", "both"}:
        result["outbound"] = codebase_trace_leg(db, symbol["id"], "outbound", depth, limit)
    if direction in {"inbound", "both"}:
        result["inbound"] = codebase_trace_leg(db, symbol["id"], "inbound", depth, limit)
    return result


def codebase_safe_source(root, rel):
    try:
        candidate = root / rel
        if candidate.is_symlink():
            return None
        source = candidate.resolve()
        if os.path.commonpath((str(root), str(source))) != str(root):
            return None
        if not source.is_file():
            return None
        return source
    except OSError:
        return None


def codebase_query_snippet(db, payload):
    value = str(payload.get("symbol", "")).strip()
    symbol, suggestions = codebase_resolve_symbol(db, value)
    if not symbol:
        return {
            "action": "snippet",
            "status": "ambiguous" if suggestions else "not_found",
            "suggestions": suggestions,
        }
    source = codebase_safe_source(REPO_ROOT.resolve(), symbol["path"])
    if not source:
        return {"action": "snippet", "status": "source_unavailable"}
    lines = source.read_text(encoding="utf-8", errors="replace").splitlines()
    neighbors = min(max(int(payload.get("neighbors", 0)), 0), 20)
    start = max(symbol["start_line"] - neighbors, 1)
    end = min(symbol["end_line"] + neighbors, len(lines), start + 499)
    current_hash = hashlib.sha256(source.read_bytes()).hexdigest()
    return {
        "action": "snippet",
        "qualified_name": symbol["qualified_name"],
        "path": symbol["path"],
        "start_line": start,
        "end_line": end,
        "source": "\n".join(lines[start - 1:end]),
        "source_freshness": "metadata_match" if current_hash == symbol["sha256"] else "changed",
    }


def codebase_normalize_rel(value):
    rel = pathlib.PurePosixPath(str(value).replace("\\", "/"))
    if rel.is_absolute() or ".." in rel.parts or not rel.parts:
        return None
    return rel.as_posix()


def codebase_query_coverage(db, payload):
    paths = payload.get("paths")
    if not isinstance(paths, list) or not paths:
        return {"action": "coverage", "errors": ["paths must be a non-empty array"]}
    results = []
    for requested in paths[:200]:
        rel = codebase_normalize_rel(requested)
        if not rel:
            results.append({"path": str(requested), "status": "invalid_path"})
            continue
        row = db.execute(
            "SELECT status,detail FROM coverage WHERE path=?", (rel,)).fetchone()
        results.append({
            "path": rel,
            "status": row["status"] if row else "not_indexed",
            "detail": row["detail"] if row else "",
            "caveat": "best_effort_not_completeness_proof",
        })
    return {"action": "coverage", "paths": results}


def codebase_query_impact(db, payload):
    requested = payload.get("paths")
    if not isinstance(requested, list) or not requested:
        requested = codebase_git_state(REPO_ROOT.resolve())["dirty_paths"]
    paths = [codebase_normalize_rel(item) for item in requested[:200]]
    paths = [item for item in paths if item]
    if not paths:
        return {"action": "impact", "paths": [], "seeds": [], "impacted": []}
    placeholders = ",".join("?" for _ in paths)
    seeds = db.execute(
        f"""SELECT s.id,s.qualified_name,f.path FROM symbols s
            JOIN files f ON f.id=s.file_id
            WHERE s.canonical_symbol_id IS NULL AND f.path IN ({placeholders})""",
        tuple(paths),
    ).fetchall()
    impacted = []
    for seed in seeds:
        impacted.extend(codebase_trace_leg(db, seed["id"], "inbound", 3, 200))
    unique = {item["qualified_name"]: item for item in impacted}
    return {
        "action": "impact",
        "paths": paths,
        "seeds": [{"qualified_name": row["qualified_name"], "path": row["path"]} for row in seeds],
        "impacted": sorted(unique.values(), key=lambda item: (item["hop"], item["qualified_name"])),
    }


def codebase_query_payload(payload):
    if not isinstance(payload, dict):
        return {"result": "codebase_query_rejected", "errors": ["payload must be an object"]}
    action = str(payload.get("action", "")).strip().lower()
    handlers = {
        "overview": codebase_query_overview,
        "search": codebase_query_search,
        "trace": codebase_query_trace,
        "snippet": codebase_query_snippet,
        "coverage": codebase_query_coverage,
        "impact": codebase_query_impact,
    }
    if action not in handlers:
        return {
            "result": "codebase_query_rejected",
            "errors": ["action must be overview, search, trace, snippet, coverage or impact"],
        }
    freshness = codebase_status_payload(payload)
    if freshness.get("status") == "missing":
        return {
            "result": "codebase_query_unavailable",
            "freshness": freshness,
            "errors": ["index is missing; run codebase-index when structural context is needed"],
        }
    db, open_error = codebase_open()
    if not db:
        return {
            "result": "codebase_query_unavailable",
            "errors": [f"index is unavailable: {open_error}"],
        }
    try:
        output = handlers[action](db, payload)
    except (sqlite3.Error, OSError, ValueError, TypeError) as exc:
        db.close()
        return {"result": "codebase_query_failed", "action": action, "errors": [str(exc)]}
    db.close()
    snippet_fresh = output.get("source_freshness") == "metadata_match"
    source_grounded = action == "snippet" and snippet_fresh
    output.update({
        "result": "codebase_query",
        "freshness": freshness.get("status"),
        "trust": "source_grounded" if source_grounded else "candidate_only",
        "coverage_signal": "best_effort",
        "source_fallback_required": (
            freshness.get("status") != "fresh"
            or (action == "snippet" and not snippet_fresh)
        ),
    })
    return output


def codebase_index(argv):
    if not argv:
        json_print({
            "result": "codebase_index_rejected",
            "errors": ["explicit JSON payload required; indexing is adaptive, never implicit"],
        })
        return
    try:
        payload, _ = json_arg_or_stdin(argv, "codebase-index")
        json_print(codebase_index_payload(payload))
    except Exception as exc:
        json_print({"result": "codebase_index_rejected", "errors": [str(exc)]})


def codebase_status(argv):
    try:
        payload = {}
        if argv:
            payload, _ = json_arg_or_stdin(argv, "codebase-status")
        json_print(codebase_status_payload(payload))
    except Exception as exc:
        json_print({"result": "codebase_status_rejected", "errors": [str(exc)]})


def codebase_query(argv):
    if not argv:
        json_print({
            "result": "codebase_query_rejected",
            "errors": ["explicit JSON payload with action is required"],
        })
        return
    try:
        payload, _ = json_arg_or_stdin(argv, "codebase-query")
        json_print(codebase_query_payload(payload))
    except Exception as exc:
        json_print({"result": "codebase_query_rejected", "errors": [str(exc)]})
